// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8FdR6U_h3gNt--PMZBDWbrC6VvrUMB6o',
    appId: '1:294319668906:web:13d80454057cb95abb5ad3',
    messagingSenderId: '294319668906',
    projectId: 'kpop-3b0b6',
    authDomain: 'kpop-3b0b6.firebaseapp.com',
    storageBucket: 'kpop-3b0b6.firebasestorage.app',
    measurementId: 'G-JHDHQ25B6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJYsiiLyZNhWxntmYEKHcHAA6-7a5QQ98',
    appId: '1:294319668906:android:97445109168e7a1bbb5ad3',
    messagingSenderId: '294319668906',
    projectId: 'kpop-3b0b6',
    storageBucket: 'kpop-3b0b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsM_x3oQVUSNB3S3SVxQV32B329k9fTnI',
    appId: '1:294319668906:ios:2e672c940051b06bbb5ad3',
    messagingSenderId: '294319668906',
    projectId: 'kpop-3b0b6',
    storageBucket: 'kpop-3b0b6.firebasestorage.app',
    androidClientId: '294319668906-hnf2fg3l1tbdhnuv8u1tq6m7ia2ao8uq.apps.googleusercontent.com',
    iosClientId: '294319668906-bdr21dqr9iopoukj7algoete7fd9mg29.apps.googleusercontent.com',
    iosBundleId: 'com.example.kHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsM_x3oQVUSNB3S3SVxQV32B329k9fTnI',
    appId: '1:294319668906:ios:2e672c940051b06bbb5ad3',
    messagingSenderId: '294319668906',
    projectId: 'kpop-3b0b6',
    storageBucket: 'kpop-3b0b6.firebasestorage.app',
    androidClientId: '294319668906-hnf2fg3l1tbdhnuv8u1tq6m7ia2ao8uq.apps.googleusercontent.com',
    iosClientId: '294319668906-bdr21dqr9iopoukj7algoete7fd9mg29.apps.googleusercontent.com',
    iosBundleId: 'com.example.kHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8FdR6U_h3gNt--PMZBDWbrC6VvrUMB6o',
    appId: '1:294319668906:web:960aaf2fa23e4c9dbb5ad3',
    messagingSenderId: '294319668906',
    projectId: 'kpop-3b0b6',
    authDomain: 'kpop-3b0b6.firebaseapp.com',
    storageBucket: 'kpop-3b0b6.firebasestorage.app',
    measurementId: 'G-V3V7EHXMX8',
  );

}